### PR TITLE
folder name fix

### LINKED ISSUE #48: "Macbook" filepath mismatch of letter cases
The file path for Macbook is actually `/macbook/` however it is referenced as `/Macbook/` in `device-mockups.css`. This will work for some web servers (esp. those commonly used in dev mode), but will fail for others (e.g. those used by Amazon for a static S3 site).

I can submit a PR, but I'm not sure whether you want a change in the LESS or in the folder naming.

It looks like this is also the case for `iPhone5/iphone5`

### PR DESCRIPTION
**Pull request by bencmbrook**
This updates folder names to be consistent with their file paths. It only changes the letter casing (which causes the file lookup to fail for some webservers).

closes #48

### CODE REVIEW

**Comment by bencmbrook** [comment]
And one thing to note-- the `imac` and `iMac` folders were combined in this PR, which moves the .PSD into the folder. I figured this combination was okay, since this is consistent with other devices' folders. The same goes for the .PSDs in `surface` and `ipad`.

In total, this PR changes
- rename `macbook` to `Macbook`
- rename `iphone` to `iPhone`
- merge `imac` into `iMac`
- merge `surface` into `Surface`
- merge `ipad` into `iPad`

**Comment by ben182** [comment]
Hi @bencmbrook,

will this affect the css image paths? Have you tested this?

**Comment by bencmbrook** [comment]
Hey @ben182, the CSS image paths remain as they were. The `data-device` attributes always used proper capitalization, so the paths always resolved to the correct capitalized case. In other words, there are no API changes and it should not break any existing projects.

I've tested this, and it's running properly now on my production server (which was failing before due to the mismatched letter casing).

And thanks for this awesome repo!

**Comment by ben182** [comment]
Okay thanks for the help!

**Pull request merged**
